use std::io::{self, Write};

use clap::CommandFactory;

#[path = "../src/cli.rs"]
mod cli;

fn main() -> io::Result<()> {
    let mut out = io::stdout().lock();
    writeln!(
        out,
        ".\\\" Generated by the manpage example; do not edit directly."
    )?;
    let mut generated = Vec::new();
    clap_mangen::Man::new(cli::Cli::command())
        .manual("User Commands")
        .render(&mut generated)?;
    // clap_mangen can emit trailing spaces in the synopsis.
    for line in String::from_utf8(generated)
        .expect("clap_mangen emits UTF-8")
        .lines()
    {
        writeln!(out, "{}", line.trim_end())?;
    }
    // Usage, options, arguments and version come from clap. Keep the additional
    // manual-only sections here so regenerating the page preserves them.
    out.write_all(
        br#".SH EXIT STATUS
.TP
.B 0
Success, including help and version requests.
.TP
.B 1
An input is invalid or cannot be read, assembly fails, or standard output
cannot be written.
.TP
.B 2
Invalid command-line arguments.
.PP
Diagnostics are written to standard error.
.SH EXAMPLES
Append a kernel package to a shim:
.PP
.EX
abl-exorcist-assembler vmlinuz abl-exorcist.bin > prepared-kernel
.EE
.PP
Build the external-initrd transport used as an Android ramdisk:
.PP
.EX
abl-exorcist-assembler --ramdisk vmlinuz initramfs.img > ablx-ramdisk.img
.EE
.SH SEE ALSO
.BR dracut (8),
.BR gzip (1),
.BR zstd (1)
.SH COPYRIGHT
Copyright holders of the abl-exorcist project.
Licensed under the GNU General Public License version 3.0 only.
"#,
    )
}
